<?php
include 'includes/config.php';
$gls=array(
	"DZ" => "Algeria",
    "AR" => "Argentina",
    "AE" => "United Arab Emirates",
    "OM" => "Oman",
    "AZ" => "Azerbaijan",
    "EG" => "Egypt",
    "IE" => "Ireland",
    "EE" => "Estonia",
    "AT" => "Austria",
    "AU" => "Australia",
    "PK" => "Pakistan",
    "BH" => "Bahrain",
    "BR" => "Brazil",
    "BY" => "Belarus",
    "BG" => "Bulgaria",
    "BE" => "Belgium",
    "IS" => "Iceland",
    "PR" => "Puerto Rico",
    "PL" => "Poland",
    "BA" => "Bosnia and Herzegovina",
    "DK" => "Denmark",
    "DE" => "Germany",
    "RU" => "Russia",
    "FR" => "France",
    "PH" => "Philippines",
    "FI" => "Finland",
    "CO" => "Colombia",
    "GE" => "Republic of Georgia",
    "KZ" => "Kazakhstan",
    "KR" => "Korea",
    "NL" => "Netherlands",
    "ME" => "Montenegro",
    "CA" => "Canada",
    "CN" => "China",
    "GH" => "Ghana",
    "CZ" => "Czech Republic",
    "ZW" => "Zimbabwe",
    "QA" => "Qatar",
    "KW" => "Kuwait",
    "HR" => "Croatia",
    "KE" => "Kenya",
    "LV" => "Latvia",
    "LB" => "Lebanese",
    "LT" => "Lithuania",
    "LY" => "Libya",
    "LU" => "The Principality of Luxembourg",
    "RO" => "Romania",
    "MY" => "Malaysia",
    "MK" => "Macedonia",
    "US" => "United States",
    "PE" => "Peru",
    "MA" => "Morocco",
    "MX" => "Mexico",
    "ZA" => "South Africa",
    "NP" => "Nepal",
    "NG" => "Nigeria",
    "NO" => "Norway",
    "PT" => "Portugal",
    "JP" => "Japan",
    "SE" => "Sweden",
    "CH" => "Switzerland",
    "RS" => "Serbia",
    "SN" => "Senegal",
    "SA" => "Saudi Arabia",
    "LK" => "Sri Lanka",
    "SK" => "Slovakia",
    "SI" => "Slovenia",
    "TW" => "Taiwan",
    "TH" => "Thailand",
    "TZ" => "Tanzania",
    "TN" => "Tunisia",
    "TR" => "Turkey",
    "UG" => "Uganda",
    "UA" => "Ukraine",
    "ES" => "Spain",
    "GR" => "Greece",
    "HK" => "Hong Kong",
    "SG" => "Singapore",
    "NZ" => "New Zealand",
    "HU" => "Hungary",
    "JM" => "Jamaica",
    "YE" => "Yemen",
    "IQ" => "Iraq",
    "IL" => "Israel",
    "IT" => "Italy",
    "IN" => "India",
    "ID" => "Indonesia",
    "GB" => "United Kingdom",
    "JO" => "Jordan",
    "VN" => "Vietnam",
    "CL" => "Chile");
$gl=(isset($_COOKIE['gl']) && $_COOKIE['gl'])?$_COOKIE['gl']: ''.$country.'';
if(!isset($gls[$gl])){$gl= ''.$country.'';}
$select[]="<select id='select_gl' class='form-control bfh-countries' style='max-width: 240px;float: right;text-align: right;margin: 0;'>";
foreach($gls as $k=>$v){
	$is_selected=($k==$gl)?' selected ':'';
	$select[]="  <option value =\"$k\"{$is_selected}>$v</option>";
}
$select[]="</select>";
echo join("\n",$select);
?>
<script>
$(document).ready(function(){$("#select_gl").change(function(){var gl=$(this).children('option:selected').val()
document.cookie="gl="+gl;window.location.reload()})})</script>
</script>
